export const mockAmbulances = [
  {
    id: 'AMB-DEL-001',
    city: 'Delhi',
    current_lat: 28.6421,
    current_lng: 77.1844,
    status: 'available',
    type: 'ALS',
    crew_readiness: 0.96,
    zone: 'North',
    equipment: ['defibrillator', 'ALS_kit', 'oxygen'],
  },
  {
    id: 'AMB-MUM-002',
    city: 'Mumbai',
    current_lat: 19.0488,
    current_lng: 72.9159,
    status: 'en_route',
    type: 'ALS',
    crew_readiness: 0.9,
    zone: 'East',
    equipment: ['defibrillator', 'oxygen', 'stretcher'],
  },
  {
    id: 'AMB-BLR-004',
    city: 'Bengaluru',
    current_lat: 12.9348,
    current_lng: 77.5751,
    status: 'available',
    type: 'BLS',
    crew_readiness: 0.83,
    zone: 'South',
    equipment: ['trauma_kit', 'oxygen', 'first_aid'],
  },
]

export const mockHospitals = [
  {
    id: 'HOSP-DEL-001',
    name: 'AIIMS Delhi',
    city: 'Delhi',
    lat: 28.5672,
    lng: 77.21,
    occupancy_pct: 75,
    er_wait_minutes: 22,
    icu_beds_available: 42,
    total_icu_beds: 198,
    diversion_status: false,
    acceptance_score: 0.82,
    specialties: ['cardiology', 'surgery', 'neurology', 'pulmonology'],
    incoming_patients: [],
  },
  {
    id: 'HOSP-MUM-006',
    name: 'Kokilaben Hospital',
    city: 'Mumbai',
    lat: 19.1219,
    lng: 72.8261,
    occupancy_pct: 70,
    er_wait_minutes: 18,
    icu_beds_available: 24,
    total_icu_beds: 60,
    diversion_status: false,
    acceptance_score: 0.79,
    specialties: ['cardiology', 'surgery', 'neurology', 'pediatrics'],
    incoming_patients: ['INC-DEMO-1'],
  },
  {
    id: 'HOSP-BLR-004',
    name: 'Fortis Hospital Bannerghatta',
    city: 'Bengaluru',
    lat: 12.8849,
    lng: 77.5987,
    occupancy_pct: 91,
    er_wait_minutes: 34,
    icu_beds_available: 4,
    total_icu_beds: 22,
    diversion_status: false,
    acceptance_score: 0.58,
    specialties: ['cardiology', 'surgery', 'neurology'],
    incoming_patients: [],
  },
]

export const mockIncidents = [
  {
    id: 'INC-DEMO-001',
    type: 'cardiac',
    severity: 'critical',
    city: 'Delhi',
    patient_count: 1,
    location_lat: 28.6139,
    location_lng: 77.209,
    description: 'Patient reports crushing chest pain and breathlessness.',
    status: 'open',
    created_at: new Date(Date.now() - 180000).toISOString(),
  },
  {
    id: 'INC-DEMO-002',
    type: 'accident',
    severity: 'high',
    city: 'Mumbai',
    patient_count: 2,
    location_lat: 19.076,
    location_lng: 72.8777,
    description: 'Road traffic accident with multiple injuries.',
    status: 'dispatched',
    created_at: new Date(Date.now() - 620000).toISOString(),
  },
]

export const mockAnalytics = {
  incidents_today: 18,
  dispatches_today: 14,
  hospitals_notified: 11,
  overloads_prevented: 3,
  avg_eta_ai: 7.4,
  avg_eta_baseline: 10.2,
  improvement_pct: 27.5,
}

export const mockBenchmark = {
  generated_at: '2024-01-15T10:30:00+00:00',
  total_incidents: 200,
  evaluation: {
    mode: 'standard',
    split: 'test',
    evaluation_dataset: 'test_incidents.json',
    evaluation_count: 200,
    training_dataset: 'train_incidents.json',
    training_count: 500,
    split_method: 'chronological (test = last 200 generated)',
    held_out: true,
    evaluation_generated_at: '2024-01-15T09:55:00+00:00',
  },
  strategies: {
    ai_dispatch: {
      avg_eta_minutes: 6.2,
      avg_total_time_minutes: 15.1,
      specialty_match_rate: 91.4,
      overload_events: 7,
      delayed_incidents: 18,
      p50_eta: 5.8,
      p90_eta: 11.6,
      p95_eta: 14.2,
      per_incident: [],
    },
    nearest_unit: {
      avg_eta_minutes: 8.7,
      avg_total_time_minutes: 18.6,
      specialty_match_rate: 64.8,
      overload_events: 31,
      delayed_incidents: 24,
      p50_eta: 8.1,
      p90_eta: 15.4,
      p95_eta: 18.9,
      per_incident: [],
    },
    random_dispatch: {
      avg_eta_minutes: 12.4,
      avg_total_time_minutes: 26.7,
      specialty_match_rate: 42.2,
      overload_events: 49,
      delayed_incidents: 39,
      p50_eta: 11.9,
      p90_eta: 23.5,
      p95_eta: 28.4,
      per_incident: [],
    },
  },
}

export const mockLiteratureComparison = {
  generated_at: '2024-01-15T11:00:00+00:00',
  papers: [
    {
      authors: 'Liu et al.',
      year: 2019,
      title: 'Dynamic ambulance redeployment and dispatching',
      journal: 'Transportation Research Part E',
      method: 'Approximate Dynamic Programming',
      method_short: 'ADP',
      improvement_over_baseline_pct: 22.4,
      context: 'Urban China, 3 cities',
      baseline: 'nearest available unit',
    },
    {
      authors: 'Schmid',
      year: 2012,
      title: 'Solving the dynamic ambulance relocation problem',
      journal: 'European Journal of Operational Research',
      method: 'Robust optimization',
      method_short: 'Robust Opt.',
      improvement_over_baseline_pct: 18.7,
      context: 'Vienna, Austria',
      baseline: 'static deployment',
    },
    {
      authors: 'Kergosien et al.',
      year: 2015,
      title: 'Generic model for online optimization of EMS',
      journal: 'Computers and Operations Research',
      method: 'Online optimization heuristic',
      method_short: 'Online Heur.',
      improvement_over_baseline_pct: 31.2,
      context: 'French metropolitan area',
      baseline: 'nearest available unit',
    },
    {
      authors: 'Maxwell et al.',
      year: 2010,
      title: 'Approximate dynamic programming for EMS',
      journal: 'INFORMS Journal on Computing',
      method: 'Approximate Dynamic Programming',
      method_short: 'ADP',
      improvement_over_baseline_pct: 26.8,
      context: 'Toronto, Canada',
      baseline: 'nearest available unit',
    },
  ],
  published_range: {
    from_year: 2010,
    to_year: 2019,
    min_improvement_pct: 18.7,
    max_improvement_pct: 31.2,
  },
  raid_nexus: {
    held_out: {
      year: 2024,
      method: 'Multi-objective scoring',
      improvement_over_baseline_pct: 27.9,
      source: 'benchmark_results.json',
    },
    cross_city: {
      year: 2024,
      method: 'Multi-objective scoring',
      improvement_over_baseline_pct: 25.8,
      source: 'cross_city_results.json',
    },
  },
  context_note:
    'Note: Direct comparison is not appropriate. Published studies use real EMS data in different urban contexts. RAID Nexus results are from synthetic data calibrated to Indian EMS statistics. The comparison is provided for situating our simulation results within the published range, not to claim equivalence.',
}

export const mockHeatmap = {
  city: 'Bengaluru',
  lookahead_minutes: 30,
  generated_at: new Date().toISOString(),
  hotspots: [
    { lat: 12.962, lng: 77.602, demand_score: 0.92, predicted_incidents: 1, cell_row: 8, cell_col: 10 },
    { lat: 12.982, lng: 77.642, demand_score: 0.78, predicted_incidents: 1, cell_row: 9, cell_col: 13 },
    { lat: 12.922, lng: 77.562, demand_score: 0.54, predicted_incidents: 0, cell_row: 5, cell_col: 7 },
  ],
  preposition_recommendations: [
    {
      ambulance_id: 'AMB-BLR-004',
      move_to_lat: 12.962,
      move_to_lng: 77.602,
      hotspot_demand_score: 0.92,
      reason: 'Move toward the highest Bengaluru hotspot with no nearby coverage.',
    },
  ],
}
